name: Build and Release

on:
  release:
    types: [created]

jobs:
  build-and-attach-assets:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Generate PocketBase db
        run: |
          wget -c https://github.com/pocketbase/pocketbase/releases/download/v0.24.1/pocketbase_0.24.1_linux_amd64.zip
          unzip -o pocketbase_0.24.1_linux_amd64.zip -d pocketbase
          pocketbase/pocketbase migrate

      - name: Install dependencies and build
        run: |
          npm install
          npm run build

      - name: Compress build output
        run: |
          zip -r home-dms-app-static-files.zip dist/public

      - name: Upload release asset
        uses: softprops/action-gh-release@v2
        with:
          files: home-dms-app-static-files.zip
